language: julia

os:
  - osx
  - linux

julia:
  - 0.7
  - 1.0
  - nightly
# matrix:
#   allowed_failures:
#     - julia: nightly

notifications:
  email: false
# uncomment the following lines to override the default test script
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.develop("Cliffords"); Pkg.develop(Pkg.PackageSpec(url="https://github.com/BBN-Q/QuantumInfo.jl")); Pkg.clone(pwd()); Pkg.build("RandomQuantum"); Pkg.test("RandomQuantum"; coverage=true)'

# necessary to run on new container-based infrastructure
sudo: false
