name = "RandomQuantum"
uuid = "7779672a-5d86-5706-9bd0-ace5ecbc1638"
authors = ["Marcus P da Silva"]
version = "0.2.0"

[deps]
Cliffords = "276b0191-6968-5de0-98fd-2a81b0f3910d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuantumInfo = "bedefb8d-ef00-5401-aa81-ae9c3f6f84cc"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Cliffords = "0.6.0"
QuantumInfo = "0.2.0"
StatsBase = "0.33.0"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
