name = "RandomQuantum"
uuid = "72df0f25-bdb7-4894-8ffd-b09139cac612"
authors = ["Marcus P da Silva"]
version = "1.0.0"

[deps]
Cliffords = "276b0191-6968-5de0-98fd-2a81b0f3910d"
QuantumInfo = "bedefb8d-ef00-5401-aa81-ae9c3f6f84cc"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Cliffords = "0.6.0"
QuantumInfo = "0.2.0"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
